# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExtractRGE
                                 A QGIS plugin
 Extraction RGE
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-18
        copyright            : (C) 2019 by Alexandre Pierson / A.GE.D.I.
        email                : alexandre.pierson@agedi.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExtractRGE class from file ExtractRGE.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .extract_rge import ExtractRGE
    return ExtractRGE(iface)
